### PR TITLE
Fix deprecation warnings on initialization

### PR DESCRIPTION
**Pull request by danelphick**
This fixes a couple of different warnings that show up in the logs.

### CODE REVIEW

**Review by tonyroberts — CHANGES_REQUESTED** [review]
For the TURN_ON/TURN_OFF flags, don't the "turn_on" and "turn_off" methods need to be implemented if those flags are set?

The way I read https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/ is that _enable_turn_on_off_backwards_compatibility should be set to False to stop those feature flags from being inferred automatically, but if the turn_on/turn_off methods are not implemented those feature flags should not be set.

Unless I'm missing something, either the turn_on/off methods need to be implemented, or the TURN_ON/TURN_OFF feature flags should not be set.

**Comment by danelphick** [comment]
From https://github.com/home-assistant/core/blob/0643ff1cfe1057617cb6fda410084022f99d9252/homeassistant/components/climate/__init__.py#L746, it looks like the service calls always exist and if `turn_off`/`turn_off` aren't overidden, it would emulate `turn_off`/`turn_on` via `HVACMode` if possible (which it would be for hawundasmart).

I thought the blog post was saying that the flag was necessary so that in the future these service calls would not be hidden. That said I find the documentation/blog posts quite terse and hard to decipher.

Just to test things out, I created a button with this config for my kitchen sensor:

```
show_name: true
show_icon: true
type: entity-button
entity: climate.kitchen
tap_action:
  service: climate.turn_on
  action: call-service
  target:
    entity_id:
      - climate.kitchen
icon: mdi:weather-night
```

I clicked the button and confirmed the result with the wunda app. The kitchen thermostat was now set to on. I changed it turn_off and clicked it again and the thermostat was set to off.

**Comment by danelphick** [comment]
All that said, I removed the flags for now. Can always add them back later if the service calls are required.

**Review by tonyroberts — APPROVED** [review]

**Comment by tonyroberts** [comment]
Thanks for the PR @danelphick! :)

**Pull request merged**
